version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ExpenseTracker.API/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=tcp:expensetracker-sqlserver.database.windows.net,1433;Initial Catalog=ExpenseTrackerDB;Persist Security Info=False;User ID=***PLACEHOLDER***;Password=***PLACEHOLDER***;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;

  client:
    build:
      context: .
      dockerfile: ExpenseTracker.Client/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

volumes:
  sqldata:
